package ui.forms;

import controller.ChatController;
import datamodel.enums.EnumMessageType;
import datamodel.pojo.User;
import java.util.List;
import ui.dialogs.JDialogServerConnect;

/**
 *
 * @author Lazar Davidovic
 */
public class JFrameMain extends javax.swing.JFrame {

    User currentUser;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain(User user) {
        this.currentUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelChat = new ui.components.panels.JPanelChat();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConnection = new javax.swing.JMenu();
        jMenuItemServerData = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuData = new javax.swing.JMenu();
        jMenuItemUserData = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenuConnection.setText("Konekcija");

        jMenuItemServerData.setText("Server");
        jMenuItemServerData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServerDataActionPerformed(evt);
            }
        });
        jMenuConnection.add(jMenuItemServerData);

        jMenuItemExit.setText("Izlaz");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuConnection.add(jMenuItemExit);

        jMenuBar1.add(jMenuConnection);

        jMenuData.setText("Podaci");

        jMenuItemUserData.setText("Korisnik");
        jMenuItemUserData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserDataActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemUserData);

        jMenuBar1.add(jMenuData);

        jMenuInfo.setText("Info");

        jMenuItemAbout.setText("O aplikaciji");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuInfo.add(jMenuItemAbout);

        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemServerDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServerDataActionPerformed
        JDialogServerConnect jdialogServerConnect = new JDialogServerConnect(this, true);
        jdialogServerConnect.setVisible(true);
        jdialogServerConnect.setLocationRelativeTo(null);

    }//GEN-LAST:event_jMenuItemServerDataActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        ChatController.showAboutWindow();
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        ChatController.offApplication();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemUserDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserDataActionPerformed
        ChatController.showUserInfo();
    }//GEN-LAST:event_jMenuItemUserDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConnection;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemServerData;
    private javax.swing.JMenuItem jMenuItemUserData;
    private ui.components.panels.JPanelChat jPanelChat;
    // End of variables declaration//GEN-END:variables

    public void fillList(List<User> users) {
        getjPanelChat().fillList(users);
    }

    public void fillHistory(EnumMessageType messageDirection, String from, String to, String text) {
        getjPanelChat().fillHistory(messageDirection, from, to, text);
    }

    /**
     * @return the jPanelChat
     */
    public ui.components.panels.JPanelChat getjPanelChat() {
        return jPanelChat;
    }

    /**
     * @param jPanelChat the jPanelChat to set
     */
    public void setjPanelChat(ui.components.panels.JPanelChat jPanelChat) {
        this.jPanelChat = jPanelChat;
    }

    
}
