package ui.dialogs;

import ui.validator.impl.Validator;

/**
 *
 * @author Lazar Davidovic
 */
public class JDialogConnection extends javax.swing.JDialog {

    /**
     * Creates new form DialogLogin
     */
    public JDialogConnection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        changePanels();
        addValidators();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDialogLogin = new javax.swing.JPanel();
        jPanelServer = new ui.components.panels.JPanelServer();
        jPanelLogin = new ui.components.panels.JPanelLogin();
        jPanelButtons = new ui.components.panels.JPanelButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanelDialogLogin.setLayout(new javax.swing.BoxLayout(jPanelDialogLogin, javax.swing.BoxLayout.Y_AXIS));
        jPanelDialogLogin.add(jPanelServer);
        jPanelDialogLogin.add(jPanelLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDialogLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDialogLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.panels.JPanelButtons jPanelButtons;
    private javax.swing.JPanel jPanelDialogLogin;
    private ui.components.panels.JPanelLogin jPanelLogin;
    private ui.components.panels.JPanelServer jPanelServer;
    // End of variables declaration//GEN-END:variables

    private void changePanels() {
        //jPanelServer.setVisible(false);
        jPanelServer.getjTextFieldServerAdress().setText("localhost");
        jPanelServer.getjTextFieldServerPortTCP().setText("1714");
        jPanelServer.getjTextFieldServerPortUDP().setText("1715");
        this.pack();
    }

    private void addValidators() {
        jPanelServer.setValidator(new Validator());
        jPanelLogin.setValidator(new Validator());
    }

    public ui.components.panels.JPanelLogin getjPanelLogin() {
        return jPanelLogin;
    }

    public ui.components.panels.JPanelServer getjPanelServer() {
        return jPanelServer;
    }

}
